repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.800'
    hooks:
    -   id: mypy
-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
    -   id: yesqa
