repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
    -   id: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
    - id: ruff
    - id: ruff-format
-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa
